Commonly used objects that enable Agile Workflows
excalidraw/excalidraw-libraries pull request #89
Opened 2021-04-14 10:30 UTC by yamatt

Adds:

- A sticky note typically used to represent a task

2021-04-20 21:28 UTC, lipis commented
A bit too simple.. no?

2021-04-21 09:29 UTC, yamatt commented
Simple and elegant.... no?

I was planning on expanding it as new features came to mind, but this one solves the problem I have for now.

Is there any kind of quality checks I'm not meeting?

2021-04-21 22:11 UTC, dwelle commented
Not necessarily quality checks in this case, but in general if it's super easy to create yourself and only contains a handful of items, it's probably a better fit for a private library. But we haven't published any guidelines yet, so...

2021-04-22 09:05 UTC, yamatt commented
To be honest it doesn't really work very well either because the text box can't be a bound width so you have to do some work with your enter key to get the text to fix the background square.

2021-06-05 09:00 UTC, dwelle commented
Let's rename this to a "sticky note" and update the description as well and we can merge!

2021-06-05 10:38 UTC, yamatt commented
Sounds good. I'll try and get around to it next week.

2021-07-29 18:28 UTC, ferminrp requested changes

2021-07-29 18:28 UTC, ferminrp commented on libraries.json
> +    "name": "Agile Workflow",
```suggestion
    "name": "Sticky Note",
```

2021-07-29 18:28 UTC, ferminrp commented on libraries.json
> +    "description": "Commonly used objects that enable Agile Workflows.",
```suggestion
    "description": "Simple and Elegant Sticky Note",
```

2021-08-13 11:38 UTC, closed without merging